[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[dev]
  command = "npm run dev" # Command to start your Vite dev server
  targetPort = 3000      # The port your Vite app runs on
  port = 8888            # The port Netlify Dev will run on
  framework = "vite"     # Explicitly specify the framework
  autoLaunch = true      # Automatically open in browser

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  node_bundler = "esbuild"
  
# Add headers for proper MIME type handling
[[headers]]
  for = "/*"
  [headers.values]
    "Access-Control-Allow-Origin" = "*"
    "Access-Control-Allow-Methods" = "GET, POST, PUT, DELETE, OPTIONS"
    "Access-Control-Allow-Headers" = "Origin, X-Requested-With, Content-Type, Accept"